Blog/Models/HomeViewModel.cs
using System.Collections.Generic;

namespace Blog.Models
{
    public class HomeViewModel
    {
        public List<Category> Categories { get; set; }

        public List<Article> NewestArticles { get; set; }

        public List<Article> MostViewedArticles { get; set; }

        public List<Tag> Tags { get; set; }
    }
}

Blog/Controllers/HomeController.cs
using Blog.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Collections.Generic;

namespace Blog.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var database = new BlogDbContext();
            var articles = database.Articles.ToList();
            var model = new HomeViewModel();
         
            model.NewestArticles = articles
                .OrderByDescending(a => a.DateCreated)
                .Take(2)
                .ToList();

            model.MostViewedArticles = articles
                .OrderByDescending(a => a.Visits)
                .Take(2)
                .ToList();

            model.Categories = database.Categories
                .OrderByDescending(c => c.Articles.Count)
                .ThenBy(c => c.Name)
                .Take(5)
                .ToList();

            model.Tags = database.Tags
                .OrderByDescending(t => t.Articles.Count)
                .ThenBy(t => t.Name)
                .Take(5)
                .ToList();

            return View(model);
        }

        public ActionResult ListCategories()
        {
            using (var database  = new BlogDbContext())
            {
                var categories = database.Categories
                    .Include(c => c.Articles)
                    .OrderBy(c => c.Name)
                    .ToList();

                return View(categories);
            }
        }
    }
}

Blog/Controllers/TagController.cs
using Blog.Models;
using System.Linq;
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class TagController : Controller
    {
        //
        //GET: Tag
        public ActionResult Index()
        {
            return RedirectToAction("All");
        }

        public ActionResult All()
        {
            using (var database = new BlogDbContext())
            {
                var tags = database.Tags.ToArray();
                if (tags == null)
                {
                    return HttpNotFound();
                }

                return View(tags);
            }
        }
    }
}

Blog/Views/Home/Index.cshtml
@model Blog.Models.HomeViewModel

@{
    ViewBag.Title = "Home";
}

<div class="container">
    <div class="row">
        <!-- Sidebar -->
        <div class="nav navbar-default col-sm-2 mt-15 pl-10 pb-10 disappearing">
            <h4 class="tcw mt-30"><span class="small">Top @Model.Categories.Count </span>Categories</h4>
            <ul class="nav navbar-default">
                @foreach (var category in Model.Categories)
                {
                    <li>@Html.ActionLink($"{category.Name} ({category.Articles.Count})", "List", "Article", new { @categoryId = category.Id }, null)</li>
                }
            </ul>
            @Html.ActionLink("See All >>", "ListCategories")

            <h4 class="tcw mt-30"><span class="small">Top @Model.Tags.Count </span>Tags</h4>
            <ul class="nav navbar-default">
                @foreach (var tag in Model.Tags)
                {
                    <li>@Html.ActionLink($"{tag.Name} ({tag.Articles.Count})", "List", "Article", new { @tagId = tag.Id }, null)</li>
                }
            </ul>
            @Html.ActionLink("See All >>", "All", "Tag")
            <hr />
            <ul class="mt-15">
                <li>
                    @Html.ActionLink("All Posts", "List", "Article", null, null)
                </li>
            </ul>
        </div>

        <div class="col-sm-10">
            <!-- Newest Articles -->
            <h2 class="text-center">Newest Articles</h2>
            @foreach (var article in Model.NewestArticles)
            {
                <div class="col-sm-6 mb-50">
                    <article>
                        <header>
                            <h3>
                                @Html.ActionLink(@article.Title, "Details", "Article", new { @id = article.Id }, null)
                            </h3>
                        </header>
                        <p>
                            @article.Summary
                        </p>
                        <footer class="author">
                            <small class="pull-left">
                                @article.DateCreated.ToString("dd.MM.yyyy")
                            </small>
                            <small class="pull-right">
                                --author @Html.ActionLink(article.Author.FullName, "List", "Article", new { @authorId = article.Author.Id }, null)
                            </small>
                        </footer>
                    </article>
                </div>
            }
        </div>
        <div class="col-sm-10">
            <!-- Most Viewed Articles -->
            <h2 class="text-center">Most Viewed</h2>
            @foreach (var article in Model.MostViewedArticles)
            {
                <div class="col-sm-6 mb-50">
                    <article>
                        <header>
                            <h3>
                                @Html.ActionLink(@article.Title, "Details", "Article", new { @id = article.Id }, null)
                            </h3>
                        </header>
                        <p>
                            @article.Summary
                        </p>
                        <footer class="author">
                            <small class="pull-left">
                                @article.DateCreated.ToString("dd.MM.yyyy")
                            </small>
                            <small class="pull-right">
                                --author @Html.ActionLink(article.Author.FullName, "List", "Article", new { @authorId = article.Author.Id }, null)
                            </small>
                        </footer>
                    </article>
                </div>
            }
        </div>

    </div>

</div>
<hr />

Blog/Views/Home/ListCategories.cshtml
@model List<Blog.Models.Category>

@{
    ViewBag.Title = "List";
}

<div class="container">
    <div class="row">
        @foreach (var category in Model)
        {
            <div class="col-sm-6 text-center text-uppercase">
                <p>
                    <h2>
                        @Html.ActionLink(string.Format($"{category.Name} ({category.Articles.Count})"),
                        "List", "Article", new { @categoryId = category.Id }, null)
                    </h2>
                </p>
            </div>
        }
    </div>
</div>
<hr />